seeds:
  ecommerce_dbt:
    schema: bronze

models:
  ecommerce_dbt:
    bronze:
      +tags: ['bronze']
      +schema: bronze
      +materialized: table
    
    silver:
      +tags: ['silver']
      +schema: silver
      +materialized: table
    
    gold:
      +tags: ['gold']
      +schema: gold
      +materialized: table